import { StyleSheet } from "react-native";
const colors = {
  primary: '#6366f1',
  text: '#111827',
  textLight: '#6b7280',
  background: '#f9fafb',
  card: '#fff'
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f9fafb' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  loadingText: { marginTop: 10, fontSize: 14, color: '#6b7280' },
  loadingSubText: { marginTop: 5, fontSize: 12, color: '#9ca3af' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  backBtn: { marginRight: 12 },
  backIcon: { fontSize: 24, color: '#6366f1' },
  headerContent: { flex: 1 },
  headerTitle: { fontSize: 18, fontWeight: '600', color: '#111827' },
  headerSubtitle: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  statusIndicator: { flexDirection: 'row', alignItems: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  dotGreen: { backgroundColor: '#10b981' },
  dotRed: { backgroundColor: '#ef4444' },
  statusText: { fontSize: 12, color: '#6b7280' },
  lastUpdate: { fontSize: 11, color: '#9ca3af' },
  mapContainer: { margin: 16 },
  sectionTitle: { fontSize: 14, fontWeight: '600', marginBottom: 8, color: '#111827' },
  map: { height: 350, borderRadius: 12 },
  infoCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    margin: 16,
    marginTop: 0,
  },
  cardTitle: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  infoLabel: { fontSize: 13, color: '#6b7280' },
  infoValue: { fontSize: 13, color: '#111827' },
  statusAccepted: { color: '#10b981', fontWeight: '600' },
  navigateBtn: {
    backgroundColor: '#10b981',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 20,
  },
  disabledBtn: { backgroundColor: '#9ca3af' },
  navigateBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  // Dans TrackingScreen.styles.js
directionsBtn: {
  backgroundColor: '#f59e0b',
  paddingVertical: 12,
  borderRadius: 12,
  alignItems: 'center',
  marginTop: 8,
},
directionsBtnText: {
  color: '#fff',
  fontWeight: '600',
  fontSize: 14,
},
mapPlaceholder: {
  width: '100%',
  height: 250,
  backgroundColor: '#f3f4f6',
  borderRadius: 12,
  justifyContent: 'center',
  alignItems: 'center',
},
mapPlaceholderIcon: {
  fontSize: 48,
  marginBottom: 12,
},
mapPlaceholderText: {
  fontSize: 14,
  color: '#6b7280',
  marginBottom: 12,
},
retryMapBtn: {
  backgroundColor: '#6366f1',
  paddingHorizontal: 20,
  paddingVertical: 8,
  borderRadius: 8,
},
retryMapBtnText: {
  color: '#fff',
  fontSize: 14,
  fontWeight: '600',
},
mapPlaceholder: {
  backgroundColor: '#f3f4f6',
  borderRadius: 12,
  padding: 20,
  alignItems: 'center',
  margin: 16,
},
mapPlaceholderIcon: {
  fontSize: 48,
  marginBottom: 12,
},
coordinatesText: {
  fontSize: 12,
  color: '#374151',
  marginVertical: 2,
  fontFamily: 'monospace',
},
mapPlaceholderText: {
  fontSize: 12,
  color: '#6b7280',
  textAlign: 'center',
  marginTop: 8,
},
});
