import { StyleSheet } from "react-native";
const colors = {
  primary: '#6366f1',
  text: '#111827'};
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f9fafb' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  backBtn: { marginRight: 12 },
  backIcon: { fontSize: 24, color: '#6366f1' },
  headerTitle: { fontSize: 18, fontWeight: '600', color: '#111827', flex: 1 },
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: 20 },
  wsStatusCard: {
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  statusRow: { flexDirection: 'row', alignItems: 'center' },
  statusLabel: { fontSize: 12, color: '#6b7280', marginRight: 8 },
  statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  dotGreen: { backgroundColor: '#10b981' },
  dotRed: { backgroundColor: '#ef4444' },
  statusText: { fontSize: 12, color: '#111827' },
  mapContainer: { margin: 16, marginBottom: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '600', marginBottom: 8, color: '#111827' },
  map: { height: 250, borderRadius: 12 },
  activationCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  cardTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 8 },
  cardDescription: { fontSize: 13, color: '#6b7280', marginBottom: 16, lineHeight: 18 },
  activateBtn: {
    backgroundColor: '#6366f1',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  activateBtnActive: { backgroundColor: '#10b981' },
  activateBtnText: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
  locationInfo: {
    marginTop: 12,
    padding: 12,
    backgroundColor: '#d1fae5',
    borderRadius: 8,
  },
  locationText: { fontSize: 12, color: '#065f46', marginBottom: 4 },
  locationCoords: { fontSize: 11, color: '#047857' },
  infoCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  donTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 4 },
  donDescription: { fontSize: 13, color: '#6b7280', marginBottom: 8 },
  donAddress: { fontSize: 12, color: '#6366f1', marginBottom: 12 },
  navigateBtn: {
    backgroundColor: '#10b981',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  navigateBtnText: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
  instructionsCard: {
    backgroundColor: '#fef3c7',
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  instructionsTitle: { fontSize: 14, fontWeight: '600', color: '#92400e', marginBottom: 8 },
  instructionsText: { fontSize: 13, color: '#78350f', lineHeight: 20 },
  messageBtn: {
    backgroundColor: '#f3f4f6',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginHorizontal: 16,
    marginBottom: 16,
  },
  messageBtnText: { color: '#6366f1', fontSize: 14, fontWeight: '600' },
  bottomSpacer: { height: 20 },
});
